version: "3.9"

services:
  risevest-backend-test:
    image: risevest-backend-test
    env_file:
      - .env
    build: ./
    ports:
      - 8080:8080
    depends_on:
      database:
        condition: service_healthy

  database:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - 5432:5432
    healthcheck:
      test:
        ["CMD-SHELL", "pg_isready -U ${DATABASE_USERNAME} -d ${DATABASE_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 55
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
